### ISSUE TITLE
Webview crash

### ISSUE THREAD

**Issue by comblock** [Pokechu22/Burger#33]
When selecting version 1.8 the packet section shows a crash log:
```Traceback (most recent call last):
  File "VFS.browser.webworker.py", line 243, in _event_handler
    self._emit_event(event_type,event.data)
  File "VFS.browser.webworker.py", line 222, in _emit_event
    self._emit(self._event_handlers,event,data)
  File "VFS.browser.webworker.py", line 231, in _emit
    h(event,data,src=self)
  File "VFS.browser.webworker.py", line 255, in _message_handler
    self._emit_message(msg.name,msg)
  File "VFS.browser.webworker.py", line 225, in _emit_message
    self._emit(self._message_handlers,message,msg)
  File "VFS.browser.webworker.py", line 231, in _emit
    h(event,data,src=self)
  File "https://pokechu22.github.io/BurgerWebViewer/brython/www/src//web_workers/worker.js/__main__", line 103, in vitrine_worker
    result = vitrine(main, main)
  File "https://pokechu22.github.io/BurgerWebViewer/brython/www/src//web_workers/worker.js/__main__", line 91, in vitrine
    return vitrine_main.generate_html(toppings, data, all_data, progress_callback=progress_callback)
  File "https://pokechu22.github.io/BurgerWebViewer/BurgerVitrine/vitrine_main.py", line 115, in generate_html
    aggregate.append(str(topping(obj, all_data, diff, wiki, highlight)))
  File "https://pokechu22.github.io/BurgerWebViewer/BurgerVitrine/vitrine/toppings/topping.py", line 37, in __str__
    return'<a href="#{1}"><h2 id="{1}">{0}</h2></a>{2}\n'.format(
  File "https://pokechu22.github.io/BurgerWebViewer/BurgerVitrine/vitrine/toppings/topping.py", line 49, in _parse_data
    aggregate += self._parse_entry(entry, key)
  File "https://pokechu22.github.io/BurgerWebViewer/BurgerVitrine/vitrine/toppings/topping.py", line 70, in _parse_entry
    return self._get_entry_html(entry, key)
  File "https://pokechu22.github.io/BurgerWebViewer/BurgerVitrine/vitrine/toppings/topping.py", line 76, in _get_entry_html
    anchor = title = self.parse_entry(entry, key)
  File "https://pokechu22.github.io/BurgerWebViewer/BurgerVitrine/vitrine/toppings/packets.py", line 151, in parse_entry
    entry["code"] = self.code(entry["instructions"])
  File "https://pokechu22.github.io/BurgerWebViewer/BurgerVitrine/vitrine/toppings/packets.py", line 36, in code
    code = self.instructions(instructions)
  File "https://pokechu22.github.io/BurgerWebViewer/BurgerVitrine/vitrine/toppings/packets.py", line 46, in instructions
    html, close, case = self.instruction(instr, close, case, level)
  File "https://pokechu22.github.io/BurgerWebViewer/BurgerVitrine/vitrine/toppings/packets.py", line 62, in instruction
    aggregate += self.indent("%s(%s);" % (
KeyError: string16```

**Comment by Pokechu22** [comment]
I've regenerated data for 1.7.10 through 1.10, which fixes the issue (`string16` was the name used by `string` prior to 72211c109b233244aed6ad96512808c5a1024f01).  I'm not sure if this also breaks other data that was previously extracted with an old version of burger but doesn't work anymore.

It looks like there might be a few other old snapshots that are affected as well (the 1.12 prereleases, some 2016 and 2017 snapshots, and a few april fools versions); if needed I can regenerate those as well.
