### ISSUE TITLE
Cannot extract biomes

### ISSUE THREAD

**Issue by psu-de** [Pokechu22/Burger#50]
I cannot extract biome data since version 1.16.2 and haven't found anything about this issue.
When running `python3 munch.py -v -d 1.20.2 -t biomes -o out.json` , out.json is missing the biome key.
Verbose output:

```
identify classes: {'nethandler.client': 'fiu', 'blockstate': 'dfj', 'particle': 'it', 'enumfacing.plane': 'ha$c', 'idmap': 'hj', 'particletypes': 'iv', 'recipe.superclass': 'me', 'nbtcompound': 'qw', 'packet.connectionstate': 'sn', 'packet.packetbuffer': 'so', 'chatcomponent': 'tl', 'metadata': 'aeh', 'identifier': 'aew', 'anvilchunkloader': 'net/minecraft/server/MinecraftServer', 'entity.trackerentry': 'akp', 'nethandler.handshake': 'alq', 'sounds.event': 'apd', 'entity.list': 'biu', 'itemstack': 'cjf', 'item.list': 'cji', 'biome.register': 'cra', 'block.list': 'csw', 'tileentity.superclass': 'dcv', 'nethandler.server': 'ded', 'blockstatecontainer': 'dfk$a', 'sounds.list': 'apd', 'biome.list': 'cra'}
Can't find file lang/stats_US.lang in jar
Can't find file lang/en_US.lang in jar
Can't find file assets/minecraft/lang/en_US.lang in jar
Can't find file assets/minecraft/lang/en_us.lang in jar
Using id '1.20.2' over name '1.20.2' for id as it is shorter
Failed to run <class 'burger.toppings.biomes.BiomeTopping'>
Traceback (most recent call last):
  File "munch.py", line 252, in <module>
    topping.act(aggregate, classloader, verbose)
  File "/home/psu/Burger/burger/toppings/biomes.py", line 53, in act
    BiomeTopping._process_114(aggregate, classloader, verbose)
  File "/home/psu/Burger/burger/toppings/biomes.py", line 500, in _process_114
    assert len(stack) == 3
AssertionError
```

For versions before `1.16.2`, everything is working fine.

**Comment by Pokechu22** [comment]
This is a known issue (but I probably should have created an issue on github for it at some point).

1.16.2 significantly changed how biomes worked internally; they are now data-driven (meaning new biomes can be added by data-packs and different worlds can have different sets of biomes). So the code Burger is looking for no longer exists.

I think that you can get biome information via [data generators](https://wiki.vg/Data_Generators) but I haven't tested it myself. It also looks like there's information in the 1.20.2 jar in `data/minecraft/worldgen/biome/`.
