### ISSUE TITLE
Jawa Exception

### ISSUE THREAD

**Issue by ObadiahCrowe** [Pokechu22/Burger#8]
Running 'python3 munch.py --download' results in:

```
Traceback (most recent call last):
  File "munch.py", line 36, in <module>
    from jawa.classloader import ClassLoader
  File "/usr/local/lib/python3.5/dist-packages/jawa/classloader.py", line 144
    with self.open(f'{path}.class') as source:
                                 ^
SyntaxError: invalid syntax

```
Is there a known fix?

**Comment by Pokechu22** [comment]
I haven't actually tested the `download` format recently; I've been manually downloading jars myself.

However, that issue appears to be due to unrecognized f-strings, which were [added in python 3.6](https://www.python.org/dev/peps/pep-0498/) (and it looks like you're using 3.5).  So, the first thing to try would be updating your python version.
